//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportationCompanyProject.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ITransportation_service")]
    public interface ITransportation_service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportation_service/Delete", ReplyAction="http://tempuri.org/ITransportation_service/DeleteResponse")]
        void Delete(TransportationCompanyProject.Model.City city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportation_service/Delete", ReplyAction="http://tempuri.org/ITransportation_service/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(TransportationCompanyProject.Model.City city);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransportation_serviceChannel : TransportationCompanyProject.ServiceReference1.ITransportation_service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Transportation_serviceClient : System.ServiceModel.ClientBase<TransportationCompanyProject.ServiceReference1.ITransportation_service>, TransportationCompanyProject.ServiceReference1.ITransportation_service {
        
        public Transportation_serviceClient() {
        }
        
        public Transportation_serviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Transportation_serviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Transportation_serviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Transportation_serviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Delete(TransportationCompanyProject.Model.City city) {
            base.Channel.Delete(city);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(TransportationCompanyProject.Model.City city) {
            return base.Channel.DeleteAsync(city);
        }
    }
}
